import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["vue", "typescript", "eslint", "promise", "vitest"],
  categories: {
    correctness: "warn",
  },
  // https://connorshea.github.io/oxlint-config-generator/
  rules: {
    "vue/block-order": [
      "error",
      {
        order: ["script", "template", "style"],
      },
    ],

    "eslint/constructor-super": "error",
    "eslint/for-direction": "error",
    "eslint/no-async-promise-executor": "error",
    "eslint/no-caller": "error",
    "eslint/no-class-assign": "error",
    "eslint/no-compare-neg-zero": "error",
    "eslint/no-cond-assign": "error",
    "eslint/no-const-assign": "error",
    "eslint/no-constant-binary-expression": "error",
    "eslint/no-constant-condition": "error",
    "eslint/no-control-regex": "error",
    "eslint/no-debugger": "error",
    "eslint/no-delete-var": "error",
    "eslint/no-dupe-class-members": "error",
    "eslint/no-dupe-else-if": "error",
    "eslint/no-dupe-keys": "error",
    "eslint/no-duplicate-case": "error",
    "eslint/no-empty-character-class": "error",
    "eslint/no-empty-pattern": "error",
    "eslint/no-empty-static-block": "error",
    "eslint/no-eval": "error",
    "eslint/no-ex-assign": "error",
    "eslint/no-extra-boolean-cast": "error",
    "eslint/no-func-assign": "error",
    "eslint/no-global-assign": "error",
    "eslint/no-import-assign": "error",
    "eslint/no-invalid-regexp": "error",
    "eslint/no-irregular-whitespace": "error",
    "eslint/no-iterator": "error",
    "eslint/no-loss-of-precision": "error",
    "eslint/no-misleading-character-class": "error",
    "eslint/no-new-native-nonconstructor": "error",
    "eslint/no-nonoctal-decimal-escape": "error",
    "eslint/no-obj-calls": "error",
    "eslint/no-self-assign": "error",
    "eslint/no-setter-return": "error",
    "eslint/no-shadow-restricted-names": "error",
    "eslint/no-sparse-arrays": "error",
    "eslint/no-this-before-super": "error",
    "eslint/no-unassigned-vars": "error",
    "eslint/no-unsafe-finally": "error",
    "eslint/no-unsafe-negation": "error",
    "eslint/no-unsafe-optional-chaining": "error",
    "eslint/no-unused-expressions": "error",
    "eslint/no-unused-labels": "error",
    "eslint/no-unused-private-class-members": "error",
    "eslint/no-unused-vars": "error",
    "eslint/no-useless-backreference": "error",
    "eslint/no-useless-catch": "error",
    "eslint/no-useless-escape": "error",
    "eslint/no-useless-rename": "error",
    "eslint/no-with": "error",
    "eslint/require-yield": "error",
    "eslint/use-isnan": "error",
    "eslint/valid-typeof": "error",
    "oxc/bad-array-method-on-arguments": "error",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "error",
    "oxc/bad-replace-all-arg": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",
    "oxc/erasing-op": "error",
    "oxc/missing-throw": "error",
    "oxc/number-arg-out-of-range": "error",
    "oxc/only-used-in-recursion": "error",
    "oxc/uninvoked-array-callback": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/triple-slash-reference": "error",
    "vitest/no-import-node-test": "error",
    "vitest/require-local-test-context-for-concurrent-snapshots": "error",
    "vue/define-emits-declaration": "error",
    "vue/define-props-declaration": "error",
    "vue/no-arrow-functions-in-watch": "error",
    "vue/no-deprecated-destroyed-lifecycle": "error",
    "vue/no-export-in-script-setup": "error",
    "vue/no-lifecycle-after-await": "error",
    "vue/no-multiple-slot-args": "error",
    "vue/no-required-prop-with-default": "error",
    "vue/prefer-import-from-vue": "error",
    "vue/require-typed-ref": "error",
    "vue/valid-define-emits": "error",
    "vue/valid-define-props": "error",
  },
});
