name: 🐞 Bug report
description: Create a report to help us improve Sulaf.
title: '[Bug]: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        This form is only for submitting bug reports. If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Read the [docs](https://sulaf.netlify.app/docs/introduction)
        - Ask on [GitHub Discussions](https://github.com/hetari/sulaf/discussions)
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is **required**, otherwise the issue might be closed without further notice. [**Why?**](https://antfu.me/posts/why-reproductions-are-required)

        To get started, you can use the StackBlitz and CodeSandbox playgrounds and share us the link.

      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages vue,@vueuse/core,radix-vue,shadcn-vue --binaries --browsers`
      render: bash
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: checkboxes
    id: contributes
    attributes:
      label: Contributes
      options:
        - label: I am willing to submit a PR to fix this issue
        - label: I am willing to submit a PR with failing tests
